version: "2.2"
services:
  master:
    image: gettyimages/spark
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8082:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  worker-1:
    image: gettyimages/spark
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8883
      SPARK_WORKER_WEBUI_PORT: 8083
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8083:8083
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
      - ./input.txt:/app/input.txt
    depends_on:
      - master

  worker-2:
    image: gettyimages/spark
    container_name: spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8884
      SPARK_WORKER_WEBUI_PORT: 8084
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8084:8084
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
      - ./input.txt:/app/input.txt
    depends_on:
      - master

  submit:
    image: gettyimages/spark
    container_name: spark-submit
    command: /app/run.sh
    hostname: submit
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8085:8085
    volumes:
      - ./input.txt:/app/input.txt
      - ./target/sample-spark-wordcount-1.0-SNAPSHOT.jar:/app/sample-spark-wordcount-1.0-SNAPSHOT.jar
      - ./run.sh:/app/run.sh
    depends_on:
      - master

